apiVersion: v1
kind: Service
metadata:
  name: mysql-conexao
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
    ClusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
  selector:
    app: php

    ---

    apiVersion: v1
    kind: Service
    metadata:
      name: loadbalancer
    spec:
      selector:
        app: php
      ports:
        - port: 80
          targetPort: 80
      type: LoadBalancer

      ---

      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: mysql-dados
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard-rwo    #Próprio do GCP